version: '3.7'

services:
  db:
    image: mariadb:10.7
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MEMORY_LIMIT: 128M
      UPLOAD_LIMIT: 64M
    restart: always
    ports:
      - "8080:80"

  php-apache:
    container_name: php-apache
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
    db_data: {}
